(ai_tiledvp 1 nil);;; 涓瑙
(ai_tiledvp 2 "_V");;;	涓や釜瑙
;;;	_-vports	骞惰

;;; 瀹涔?->->....榧->?->瀹? bedit->refedit

;;;	(setvar "orthomode" (abs (1- (getvar "orthomode"))))



(defun C:1 (/ gp)
	(setvar "cmdecho" 0)
	(princ "\n瑰瀵硅薄棰蹭负绾㈣测?")
	(setq gp (ssget))
	(if (/= gp nil) (command ".change" gp "" "p" "c" "1" ""))
	(princ "\nOK")
	(princ)
);end defun C:1 




;;; 灏瀛杞虫瑙搴?
;;;	50-瑙搴锛?51-炬瑙搴
;;;	TODO锛╁硅薄
(defun c:aaaalign-textangle (/ A B)
	(setq A (ssget))
	(setq B (getangle "瀹绗涓?:<E:east>\n"))
	(defun changebyanlge (/ i)
		(defun change-angle (new-rad ent-data)
			(entmod (subst
					(cons 50 new-rad)
					(assoc 50 ent-data)
					ent-data)))
		(setq i 0)
		(repeat (sslength A)
			(progn
				(change-angle B (entget (ssname A i)))
				(setq i (1+ i)))))
	(changebyanlge))

(defun c:ddf (/ A B)
	(princ "瀹瑕淇瑰硅?:")
	(setq A (ssget))
	(princ "瀹瀵硅薄:")
	(setq B (ssget))
	(changebyobject)
	(defun changebyobject (/ i)
		(setq i 0)
		(repeat (sslength A)
			(progn
				(entmod (subst
						(assoc 50 (entget (ssname B 0)))
						(assoc 50 (entget (ssname A i)))
						(entget (ssname A i))))
				(setq i (1+ i)))))
)





(defun align-text-angle (/ A B)
;;;	Judge witch mode
	(nil)
	(defun changebyanlge (/ i);;;	Change by anlge
		(defun change-angle (new-rad ent-data)
			(entmod (subst
					(cons 50 new-rad)
					(assoc 50 ent-data)
					ent-data)))
		(setq i 0)
		(repeat (sslength A)
			(progn
				(change-angle B (entget (ssname A i)))
				(setq i (1+ i)))))
	(defun changebyobject (/ i);;;	Change by object
		(setq i 0)
		(repeat (sslength A)
			(progn
				(entmod (subst
						(assoc 50 (entget (ssname B 0)))
						(assoc 50 (entget (ssname A i)))
						(entget (ssname A i))))
				(setq i (1+ i))))))



;;;	选择集 selectset -> ssget
;;;	图元（对象） -> 
;;;	对象名 -> ssname
;;;	对象的定义数据ent -> entget
;;;	assoc  cdr




;;; 计算表达式值
;;;	maybe can use foreach funcation
;;;	add setting of accuracy 
;;;	subset x by * (more in cutstr)
(defun calc-text (/ A i text)
	(setq A (ssget))
	(defun cutstr (str)
		(substr str 1 (VL-String-Search "=" str)))
	(setq i 0)
	(repeat (sslength A)
		(progn
			(setq text (cutstr (get-obj-att (ssname A i) 1)))
			(set-obj-att
				(ssname A i)
				1
				(strcat text "=" (rtos (cal text) 2 3)))
			(setq i (1+ i)))))
;;;	get attribute of object
(defun get-obj-att (Obj num)
	(cdr (assoc num (entget Obj))))
;;;	set attribute of object
(defun set-obj-att (Obj num att)
	(entmod (subst
			(cons num att)
			(assoc num (entget Obj))
			(entget Obj))))
;;;	查询对应属性
(defun )
